export default interface User {
    firstName: string,
    lastName: string,
    email: string,
    password: string,
    role?: string,
    birthDate: string | Date,
    address: string,
    country: string,
    city: string,
    countryCode: string,
    zipCode: Number,
    phoneNo1: string,
    phoneNo2?: string,
    image?: string,
}
